package my.tz.yaspellmockservice.contract;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-08-23T22:44:00.664+03:00
 * Generated source version: 3.1.7
 * 
 */
@WebServiceClient(name = "SpellService", 
                  wsdlLocation = "file:/C:/LocalSource/Java/YaSpellMockService/src/main/java/my/tz/yaspellmockservice/contract/yaspellmockservice.wsdl",
                  targetNamespace = "http://tomee.local/services/spellMock/services") 
public class SpellService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tomee.local/services/spellMock/services", "SpellService");
    public final static QName SpellServiceSoap = new QName("http://tomee.local/services/spellMock/services", "SpellServiceSoap");
    public final static QName SpellServiceSoap12 = new QName("http://tomee.local/services/spellMock/services", "SpellServiceSoap12");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/LocalSource/Java/YaSpellMockService/src/main/java/my/tz/yaspellmockservice/contract/yaspellmockservice.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SpellService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/LocalSource/Java/YaSpellMockService/src/main/java/my/tz/yaspellmockservice/contract/yaspellmockservice.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SpellService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SpellService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SpellService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public SpellService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SpellService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SpellService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns SpellServiceSoap
     */
    @WebEndpoint(name = "SpellServiceSoap")
    public SpellServiceSoap getSpellServiceSoap() {
        return super.getPort(SpellServiceSoap, SpellServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SpellServiceSoap
     */
    @WebEndpoint(name = "SpellServiceSoap")
    public SpellServiceSoap getSpellServiceSoap(WebServiceFeature... features) {
        return super.getPort(SpellServiceSoap, SpellServiceSoap.class, features);
    }


    /**
     *
     * @return
     *     returns SpellServiceSoap
     */
    @WebEndpoint(name = "SpellServiceSoap12")
    public SpellServiceSoap getSpellServiceSoap12() {
        return super.getPort(SpellServiceSoap12, SpellServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SpellServiceSoap
     */
    @WebEndpoint(name = "SpellServiceSoap12")
    public SpellServiceSoap getSpellServiceSoap12(WebServiceFeature... features) {
        return super.getPort(SpellServiceSoap12, SpellServiceSoap.class, features);
    }

}
