
package my.tz.yaspellmockservice.contract;

import javax.xml.ws.Endpoint;
import my.tz.yaspellmockservice.impl.SpellServiceSoapImpl;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-08-23T22:44:00.651+03:00
 * Generated source version: 3.1.7
 * 
 */
 
public class SpellServiceSoap_SpellServiceSoap_Server{

    protected SpellServiceSoap_SpellServiceSoap_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new SpellServiceSoapImpl();
        String address = "http://tomee.local/services/spellMock/services";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new SpellServiceSoap_SpellServiceSoap_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
